version: "3"

services:
  db:
    image: postgres:13.2-alpine
    container_name: chip-db 
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    networks:
      - chip-network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chip-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - chip-network
networks:
  chip-network:
    name: chip-network
    driver: bridge
